reference_rule <- function(
  availability = "stored",
  source_configuration = list(),
  reason = NULL
) {
  list(
    availability = availability,
    source_configuration = source_configuration,
    reason = reason
  )
}

funconstrain_problem_manifest <- function() {
  data.frame(
    number = seq_len(35L),
    name = c(
      "rosen",
      "freud_roth",
      "powell_bs",
      "brown_bs",
      "beale",
      "jenn_samp",
      "helical",
      "bard",
      "gauss",
      "meyer",
      "gulf",
      "box_3d",
      "powell_s",
      "wood",
      "kow_osb",
      "brown_den",
      "osborne_1",
      "biggs_exp6",
      "osborne_2",
      "watson",
      "ex_rosen",
      "ex_powell",
      "penalty_1",
      "penalty_2",
      "var_dim",
      "trigon",
      "brown_al",
      "disc_bv",
      "disc_ie",
      "broyden_tri",
      "broyden_band",
      "linfun_fr",
      "linfun_r1",
      "linfun_r1z",
      "chebyquad"
    ),
    title = c(
      "Rosenbrock Function",
      "Freudenstein and Roth Function",
      "Powell Badly Scaled Function",
      "Brown Badly Scaled Function",
      "Beale Function",
      "Jennrich and Sampson Function",
      "Helical Valley Function",
      "Bard Function",
      "Gaussian Function",
      "Meyer Function",
      "Gulf Research and Development Function",
      "Box Three-Dimensional Function",
      "Powell Singular Function",
      "Wood Function",
      "Kowalik and Osborne Function",
      "Brown and Dennis Function",
      "Osborne 1 Function",
      "Biggs EXP6 Function",
      "Osborne 2 Function",
      "Watson Function",
      "Extended Rosenbrock Function",
      "Extended Powell Function",
      "Penalty Function I",
      "Penalty Function II",
      "Variably Dimensioned Function",
      "Trigonometric Function",
      "Brown Almost-Linear Function",
      "Discrete Boundary Value Function",
      "Discrete Integral Equation Function",
      "Broyden Tridiagonal Function",
      "Broyden Banded Function",
      "Linear Function - Full Rank",
      "Linear Function - Rank 1",
      "Linear Function - Rank 1 with Zero Columns and Rows",
      "Chebyquad Function"
    ),
    n_kind = c(rep("fixed", 19L), rep("variable", 16L)),
    n_default = c(
      2L,
      2L,
      2L,
      2L,
      2L,
      2L,
      3L,
      3L,
      3L,
      3L,
      3L,
      3L,
      4L,
      4L,
      4L,
      4L,
      5L,
      6L,
      11L,
      6L,
      8L,
      20L,
      25L,
      25L,
      30L,
      30L,
      30L,
      35L,
      35L,
      40L,
      40L,
      45L,
      45L,
      45L,
      50L
    ),
    n_min = c(
      2L,
      2L,
      2L,
      2L,
      2L,
      2L,
      3L,
      3L,
      3L,
      3L,
      3L,
      3L,
      4L,
      4L,
      4L,
      4L,
      5L,
      6L,
      11L,
      2L,
      2L,
      4L,
      rep(1L, 13L)
    ),
    n_max = c(
      2L,
      2L,
      2L,
      2L,
      2L,
      2L,
      3L,
      3L,
      3L,
      3L,
      3L,
      3L,
      4L,
      4L,
      4L,
      4L,
      5L,
      6L,
      11L,
      31L,
      rep(Inf, 15L)
    ),
    n_multiple = c(rep(1L, 20L), 2L, 4L, rep(1L, 13L)),
    m_kind = c(
      rep("fixed", 5L),
      "configurable",
      rep("fixed", 4L),
      rep("configurable", 2L),
      rep("fixed", 3L),
      "configurable",
      "fixed",
      "configurable",
      rep("fixed", 2L),
      rep("derived", 11L),
      rep("configurable", 3L),
      "derived"
    ),
    m_default = c(
      2L,
      2L,
      2L,
      3L,
      3L,
      10L,
      3L,
      15L,
      15L,
      16L,
      99L,
      20L,
      4L,
      6L,
      11L,
      20L,
      33L,
      13L,
      65L,
      31L,
      8L,
      20L,
      26L,
      50L,
      32L,
      30L,
      30L,
      35L,
      35L,
      40L,
      40L,
      100L,
      100L,
      100L,
      50L
    ),
    m_min = c(
      2L,
      2L,
      2L,
      3L,
      3L,
      2L,
      3L,
      15L,
      15L,
      16L,
      3L,
      3L,
      4L,
      6L,
      11L,
      4L,
      33L,
      6L,
      65L,
      31L,
      rep(NA_integer_, 11L),
      rep(1L, 3L),
      NA_integer_
    ),
    m_max = c(
      2L,
      2L,
      2L,
      3L,
      3L,
      Inf,
      3L,
      15L,
      15L,
      16L,
      100L,
      Inf,
      4L,
      6L,
      11L,
      Inf,
      33L,
      Inf,
      65L,
      31L,
      rep(NA_real_, 11L),
      rep(Inf, 3L),
      NA_real_
    ),
    m_multiple = c(
      rep(1L, 20L),
      rep(NA_integer_, 11L),
      rep(1L, 3L),
      NA_integer_
    ),
    m_n_multiplier = c(
      rep(NA_integer_, 20L),
      1L,
      1L,
      1L,
      2L,
      1L,
      1L,
      1L,
      1L,
      1L,
      1L,
      1L,
      rep(NA_integer_, 3L),
      1L
    ),
    m_n_offset = c(
      rep(NA_integer_, 20L),
      0L,
      0L,
      1L,
      0L,
      2L,
      rep(0L, 6L),
      rep(NA_integer_, 3L),
      0L
    ),
    m_gte_n = c(
      rep(FALSE, 5L),
      TRUE,
      rep(FALSE, 5L),
      TRUE,
      rep(FALSE, 3L),
      TRUE,
      FALSE,
      TRUE,
      rep(FALSE, 13L),
      rep(TRUE, 3L),
      FALSE
    ),
    fmin_reference = I(list(
      reference_rule(),
      reference_rule(),
      reference_rule(),
      reference_rule(),
      reference_rule(),
      reference_rule(source_configuration = list(m = 10L)),
      reference_rule(),
      reference_rule(),
      reference_rule(),
      reference_rule(),
      reference_rule(),
      reference_rule(),
      reference_rule(),
      reference_rule(),
      reference_rule(),
      reference_rule(source_configuration = list(m = 20L)),
      reference_rule(),
      reference_rule(),
      reference_rule(),
      reference_rule(source_configuration = list(n = 6L)),
      reference_rule(),
      reference_rule(),
      reference_rule(source_configuration = list(n = 4L)),
      reference_rule(source_configuration = list(n = 4L)),
      reference_rule(),
      reference_rule(),
      reference_rule(),
      reference_rule(),
      reference_rule(),
      reference_rule(),
      reference_rule(),
      reference_rule(source_configuration = list(n = 4L, m = 100L)),
      reference_rule(source_configuration = list(m = 100L)),
      reference_rule(source_configuration = list(n_min = 3L, m = 100L)),
      reference_rule(source_configuration = list(n = 8L))
    )),
    xmin_reference = I(list(
      reference_rule(),
      reference_rule(),
      reference_rule(),
      reference_rule(),
      reference_rule(),
      reference_rule(source_configuration = list(m = 10L)),
      reference_rule(),
      reference_rule(),
      reference_rule(),
      reference_rule(),
      reference_rule(),
      reference_rule(
        availability = "unavailable",
        reason = "no_single_minimizer"
      ),
      reference_rule(),
      reference_rule(),
      reference_rule(),
      reference_rule(source_configuration = list(m = 20L)),
      reference_rule(),
      reference_rule(),
      reference_rule(),
      reference_rule(source_configuration = list(n = 6L)),
      reference_rule(source_configuration = list(n = 8L)),
      reference_rule(source_configuration = list(n = 4L)),
      reference_rule(source_configuration = list(n = 4L)),
      reference_rule(source_configuration = list(n = 4L)),
      reference_rule(source_configuration = list(n = 6L)),
      reference_rule(source_configuration = list(n = 4L)),
      reference_rule(source_configuration = list(n = 4L)),
      reference_rule(source_configuration = list(n = 5L)),
      reference_rule(source_configuration = list(n = 5L)),
      reference_rule(source_configuration = list(n = 5L)),
      reference_rule(source_configuration = list(n = 5L)),
      reference_rule(source_configuration = list(n = 4L, m = 100L)),
      reference_rule(source_configuration = list(n = 5L, m = 100L)),
      reference_rule(source_configuration = list(n = 5L, m = 100L)),
      reference_rule(source_configuration = list(n = 8L))
    )),
    stringsAsFactors = FALSE
  )
}
